### ISSUE TITLE
set max execution time of a request

### ISSUE THREAD

**Issue by thebennos** [vizzbuzz/tutum-workqueue#2]
Limits: max execution time of a request  (if the job is to request a webpage then it would be a good thing)

**Comment by neilellis** [comment]
Sure so this would translate to a timeout on curl itself. Again perfectly reasonable request.

**Comment by neilellis** [comment]
I'm not going to add this as a per job request as I think that add's more complexity than I need to. But I will make this an ENV var.

**Comment by neilellis** [comment]
This is now added as the ENV var REMOTE_REQUEST_TIMEOUT which defaults to 300 (seconds)
